export const GAME_CONSTANTS = {
  ACCELERATION: 60,
  MAX_SPEED: 120,
  BOOST_MULTIPLIER: 1.8,
  BRAKE_FORCE: 0.9,
  ROTATION_SPEED: 0.04,
  STAR_COUNT: 5000,
  STAR_SPEED_BASE: 0.5,
  STAR_SPREAD: 500,
  
  // Racing Constants
  RACE_DISTANCE: 1000, // Z-coordinate distance to the finish disk
  FINISH_DISK_RADIUS: 50,
  AI_SPEED_MULTIPLIER: 0.85,
  AI_COUNT: 5,

  // AI behavior tuning
  AI_SPEED_VARIANCE: 0.2,
  AI_LATERAL_SWAY_AMPLITUDE: 4,
  AI_LATERAL_SWAY_FREQUENCY: 0.5,
  AI_INITIAL_Z_MIN: -60,
  AI_INITIAL_Z_MAX: -20,
} as const